# Generated by Django 6.0.7 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Institution', 'Institution'), ('Government', 'Government')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
