# Generated by Django 6.0.7 on 2026-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='source',
            field=models.CharField(blank=True, help_text='Purchase or Donated by...', max_length=255),
        ),
    ]
