# Generated by Django 6.0.7 on 2026-07-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_libraryitem_date_added_libraryitem_serial_number_and_more'),
        ('donors', '0002_donor_department_donor_designation_donor_donor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_books', to='donors.donor'),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
