# Generated by Django 6.0.7 on 2026-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_libraryitem_donor_delete_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Issued', 'Issued'), ('Pending Pickup', 'Pending Pickup'), ('Maintenance', 'Maintenance'), ('Archived', 'Archived')], default='Available', max_length=20),
        ),
    ]
