# Generated by Django 6.0.7 on 2026-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0002_bookrequest_rejected_at_bookrequest_rejected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Ready for Pickup', 'Ready for Pickup'), ('Collected', 'Collected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
