# Generated by Django 6.0.7 on 2026-07-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
    ]
