# Generated by Django 6.0.7 on 2026-08-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_designation_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head_librarian', 'Head Librarian'), ('library_helper', 'Library Helper'), ('member', 'Member')], default='member', max_length=30),
        ),
    ]
