# Generated by Django 6.0.7 on 2026-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_librarian_return_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending Pickup', 'Pending Pickup'), ('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=20),
        ),
    ]
