# Generated by Django 6.0.7 on 2026-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
