# Generated by Django 6.0.7 on 2026-08-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
